[JIR-3] fake ticket test

diff --git a/.github/workflows/commit_check.yaml b/.github/workflows/commit_check.yaml
--- a/.github/workflows/commit_check.yaml
+++ b/.github/workflows/commit_check.yaml
@@ -5,8 +5,8 @@ on:
       - jira-checker
       
 env:
-  atlassian_user: brytboy@github.com
-  atlassian_key: 9MGgvvK0k38Sw3zYqDMmA485
+  atlassian_user: ${{ secrets.ATLASSIAN_USER }}
+  atlassian_key: ${{ secrets.ATLASSIAN_KEY }}
   atlassian_url: team-1624462930934.atlassian.net
       
 jobs:
@@ -27,9 +27,10 @@ jobs:
           echo $ISSUE_STATUS
           if [[ $ISSUE_STATUS == '"To Do"' ]] || [[ $ISSUE_STATUS == '"In Progress"' ]]
           then
-            EVENT_MESSAGE="{\"body\":\"New GitHub work has been linked to this issue: https://github.com/BrytBoyCorp/github-actions/commit/${GITHUB_SHA}\"}"
+            EVENT_MESSAGE="{\"body\":\"New GitHub work has been linked to this issue: https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}\"}"
             curl -X POST -u "${{ env.atlassian_user }}:${{ env.atlassian_key }}" -H "Accept:application/json" -H "Content-Type:application/json" -d "${EVENT_MESSAGE}" "https://${{ env.atlassian_url }}/rest/api/2/issue/${ISSUE}/comment"
           else
-            echo "JIRA issue does not appear to be in an active sprint. Instead the issue status is: ${ISSUE_STATUS} -- Exiting..."
+            echo "JIRA issue does not appear to be an active sprint work item. Instead the issue status is: ${ISSUE_STATUS} -- failing operation."
+            exit 1
           fi
              
