[JIR-1] test

diff --git a/.github/workflows/jira_check.yaml b/.github/workflows/jira_check.yaml
--- a/.github/workflows/jira_check.yaml
+++ b/.github/workflows/jira_check.yaml
@@ -21,12 +21,17 @@ jobs:
           COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
           COMMIT_MESSAGE=${COMMIT_MESSAGE#*\[}
           ISSUE=${COMMIT_MESSAGE%\]*}
+          if [ $ISSUE == "" ]
+          then
+            echo "Commit message did not contain a valid JIRA issue key in the expected format: [JIRA-KEY] -- failing operation."
+            exit 1
+          fi
           ISSUE_STATUS=$(curl -u "${{ env.atlassian_user }}:${{ env.atlassian_key }}" -H "Content-Type:application/json" "https://${{ env.atlassian_url }}/rest/api/2/issue/${ISSUE}" | jq '.fields.status.name')
-              
+          echo $ISSUE_STATUS
           if [[ $ISSUE_STATUS == "To Do" ]] || [[ $ISSUE_STATUS == "In Progress" ]]
           then
             curl -X POST -u "${{ env.atlassian_user }}:${{ env.atlassian_key }}" -H "Accept:application/json" -H "Content-Type:application/json" -d '{"body":"New GitHub work has been linked to this issue: https://github.com/BrytBoyCorp/github-actions/commit/${GITHUB_SHA}"}' "https://${{ env.atlassian_url }}/rest/api/2/issue/${ISSUE}/comment"
           else
-            echo "Commit message did not contain a valid JIRA issue key in the expected format: [JIRA-KEY] -- failing operation."
+            echo "JIRA issue does not appear to be in an active sprint -- failing operation."
           fi
              
